SET NAMES utf8mb4;
-- Docker demo bootstrap only. The complete schema source of truth is backend/src/main/resources/db/migration.
-- For manual setup, let the backend run Flyway migrations first, then use this script for demo data.
CREATE DATABASE IF NOT EXISTS issue_ops DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE issue_ops;
CREATE TABLE IF NOT EXISTS issue (id BIGINT PRIMARY KEY AUTO_INCREMENT,issue_no VARCHAR(40) NOT NULL UNIQUE,title VARCHAR(255) NOT NULL,description TEXT,source VARCHAR(50),business_scene VARCHAR(100),issue_type VARCHAR(50),impact_scope VARCHAR(100),customer_impact TEXT,reproduce_steps TEXT,priority VARCHAR(10),status VARCHAR(30),responsible_department VARCHAR(60),responsible_person VARCHAR(60),tapd_url VARCHAR(500),attachment_url VARCHAR(500),root_cause TEXT,fix_solution TEXT,verify_result TEXT,is_reopened TINYINT(1) DEFAULT 0,reopened_reason TEXT,expected_finish_time DATETIME,actual_finish_time DATETIME,created_by VARCHAR(60),created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted TINYINT(1) DEFAULT 0,INDEX idx_status(status),INDEX idx_department(responsible_department),INDEX idx_expected(expected_finish_time));
CREATE TABLE IF NOT EXISTS issue_log (id BIGINT PRIMARY KEY AUTO_INCREMENT,issue_id BIGINT NOT NULL,action_type VARCHAR(50),content TEXT,operator VARCHAR(60),created_at DATETIME DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_issue_log_issue FOREIGN KEY(issue_id) REFERENCES issue(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS ai_insight_session (id VARCHAR(64) PRIMARY KEY,insight_id VARCHAR(64),title VARCHAR(255),created_at DATETIME DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_ai_insight_session_insight(insight_id));
CREATE TABLE IF NOT EXISTS ai_insight_message (id BIGINT PRIMARY KEY AUTO_INCREMENT,session_id VARCHAR(64) NOT NULL,role VARCHAR(20) NOT NULL,content MEDIUMTEXT,structured_json MEDIUMTEXT,model VARCHAR(100),generated_by VARCHAR(60),created_at DATETIME DEFAULT CURRENT_TIMESTAMP,INDEX idx_ai_insight_message_session(session_id,id));
INSERT IGNORE INTO issue(id,issue_no,title,description,source,business_scene,issue_type,impact_scope,customer_impact,reproduce_steps,priority,status,responsible_department,responsible_person,tapd_url,root_cause,fix_solution,verify_result,is_reopened,expected_finish_time,actual_finish_time,created_by,created_at) VALUES
(1,'PBI-20260601-0001','支付成功后订单状态延迟更新','用户支付成功后订单长时间停留在待支付状态。','客服反馈','订单支付','系统缺陷','部分用户','影响订单查询并引发重复支付咨询','1. 完成支付\n2. 返回订单页\n3. 刷新订单状态','P0','处理中','交易平台','张霖','https://tapd.example.com/1','消息消费积压导致状态同步延迟','增加幂等消费与积压告警',NULL,0,DATE_ADD(NOW(),INTERVAL 2 DAY),NULL,'客服-林悦',DATE_SUB(NOW(),INTERVAL 3 DAY)),
(2,'PBI-20260602-0002','优惠券领取后无法使用','部分活动券规则配置冲突。','客户反馈','营销活动','产品缺陷','部分客户','下单转化受影响','领取优惠券后进入结算页','P1','待验证','产品部','李娜','https://tapd.example.com/2','规则优先级冲突','统一规则校验并补充提示','测试环境验证通过',0,DATE_ADD(NOW(),INTERVAL 1 DAY),NULL,'运营-王芳',DATE_SUB(NOW(),INTERVAL 5 DAY)),
(3,'PBI-20260603-0003','批量导入用户偶发失败','大文件导入时接口超时。','监控告警','用户运营','性能问题','内部用户','运营任务延迟','导入超过5000行的模板','P1','处理中','技术部','陈晨','https://tapd.example.com/3','同步处理超时','改为异步任务并增加进度反馈','压测通过',1,DATE_SUB(NOW(),INTERVAL 1 DAY),NULL,'系统监控',DATE_SUB(NOW(),INTERVAL 8 DAY)),
(4,'PBI-20260604-0004','消息推送到达率下降','安卓端部分通道到达率下降。','数据巡检','消息触达','第三方服务','部分用户','活动触达下降','后台发送活动推送','P2','待处理','技术部','刘洋','https://tapd.example.com/4',NULL,NULL,NULL,0,DATE_ADD(NOW(),INTERVAL 4 DAY),NULL,'数据平台',DATE_SUB(NOW(),INTERVAL 1 DAY)),
(5,'PBI-20260605-0005','导出报表字段缺失','新增字段未同步至导出模板。','业务反馈','数据报表','需求遗漏','内部用户','人工补数成本增加','选择全字段导出','P2','已完成','数据部','周婷','https://tapd.example.com/5','模板字段映射遗漏','统一字段元数据驱动导出','生产验证通过',0,DATE_SUB(NOW(),INTERVAL 2 DAY),DATE_SUB(NOW(),INTERVAL 1 DAY),'运营-赵敏',DATE_SUB(NOW(),INTERVAL 10 DAY));
INSERT IGNORE INTO issue_log(id,issue_id,action_type,content,operator,created_at) VALUES (1,1,'创建问题','客服反馈支付状态未更新','林悦',DATE_SUB(NOW(),INTERVAL 3 DAY)),(2,1,'状态变更','待处理 → 处理中','张霖',DATE_SUB(NOW(),INTERVAL 2 DAY)),(3,2,'验证记录','测试环境验证通过，等待生产观察','测试组',DATE_SUB(NOW(),INTERVAL 1 DAY)),(4,3,'复发记录','相同导入问题再次出现','系统监控',DATE_SUB(NOW(),INTERVAL 2 HOUR));
